apiVersion: v1
kind: Secret
metadata:
  name: authentication-service-secret
type: Opaque
data:
  DB_USER: bXlzcWx1c2Vy
  DB_PASS: bXlwYXNz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  labels:
    app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: hassanhbahmed/authentication-service:latest
          ports:
            - containerPort: 7000
          env:
            - name: DB_HOST
              value: "mysql-db"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: authentication-service-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: authentication-service-secret
                  key: DB_PASS
            - name: DB_SCHEMA
              value: "ecommerce_app_database"
            - name: ACTIVE_PROFILE
              value: "dev"
            - name: PORT
              value: "7000"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-service
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30003
  type: NodePort
