apiVersion: v1
kind: Secret
metadata:
  name: react-ui-secret
type: Opaque
data:
  REACT_APP_STRIPE_PUBLISH_KEY: cGtfdGVzdF81MUx0RkVoSzNSMEpZalV1WktRZDFVNFpHWEZPZjZyM2FnSUh4dEd2SzVBeDBURWtUdkxQUEczbUVPUEdERDQ4WDdSNlpQMk9sQWN4OE05RzNVMEI4MUZDTTAwRm1LV2ZjQWU=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
spec:
  selector:
    matchLabels:
      app: react-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
        - name: react-ui
          image: hassanhbahmed/react-ui:latest
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_STRIPE_PUBLISH_KEY
              valueFrom:
                secretKeyRef:
                  name: react-ui-secret
                  key: REACT_APP_STRIPE_PUBLISH_KEY
            - name: REACT_APP_COMMON_DATA_SERVICE_PORT
              value: "9000"
            - name: REACT_APP_ENVIRONMENT
              value: "dev"
---
apiVersion: v1
kind: Service
metadata:
  name: react-ui
spec:
  selector:
    app: react-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
