name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Minikube
      env:
          PRIVATE_KEY: ${{ secrets.PEM_FILE }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          REACT_CLIENT_URL_SECRET: ${{ vars.REACT_CLIENT_URL_SECRET }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "sudo minikube start --driver=docker --cpus=2 --memory=6144 --force"
        ssh -i private_key -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "sudo kubectl delete -f /home/ubuntu/CICD/myfyp/minikube/ && sleep 60"
        ssh -i private_key -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "sudo sed -i 's|REACT_CLIENT_URL_PLACEHOLDER|'$REACT_CLIENT_URL_SECRET'|g' /home/ubuntu/CICD/myfyp/minikube/common.yaml"
        ssh -i private_key -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "sudo kubectl apply -f /home/ubuntu/CICD/myfyp/minikube"
        ssh -i private_key -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "sudo sed -i 's|'$REACT_CLIENT_URL_SECRET'|REACT_CLIENT_URL_PLACEHOLDER|g' /home/ubuntu/CICD/myfyp/minikube/common.yaml"
